package shutdown;


import java.awt.Color;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.io.IOException;
import java.net.URI;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Menu.java
 *
 * Created on Dec 17, 2012, 6:46:08 PM
 */

/**
 *
 * @author AJAY
 */
public class Menu extends javax.swing.JFrame {

    /** Creates new form Menu */
    public Menu() {
        try{
        Runtime.getRuntime().exec("exit");
        }
        catch(Exception e)
        {}
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aboutUsPop = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        aboutUsText = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        knowUs = new javax.swing.JTextPane();
        jButton2 = new javax.swing.JButton();
        authorPop = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        restart = new javax.swing.JButton();
        shutdown = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        hibernate = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        aboutUsPop.setResizable(false);
        aboutUsPop.setUndecorated(true);

        aboutUsText.setColumns(20);
        aboutUsText.setEditable(false);
        aboutUsText.setFont(new java.awt.Font("Courier New", 0, 16));
        aboutUsText.setRows(5);
        aboutUsText.setText(" fWin8Hibernate is the is win8-based \n Application,which enables you\n to hibernate your System which you\n were missing in Win8...\n It also makes your System to Boot \n fatser ....\n \t\t    \t    This is \n        \t© forward s/ash inc.\n\t\t   \t    product.\n\t     \t     (version 1.0.0)");
        aboutUsText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aboutUsTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aboutUsTextMouseExited(evt);
            }
        });
        jScrollPane2.setViewportView(aboutUsText);

        knowUs.setEditable(false);
        knowUs.setFont(new java.awt.Font("Lucida Handwriting", 1, 24));
        knowUs.setForeground(java.awt.Color.red);
        knowUs.setText("Know Us.");
        knowUs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                knowUsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                knowUsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                knowUsMouseExited(evt);
            }
        });
        jScrollPane3.setViewportView(knowUs);

        jButton2.setBackground(java.awt.Color.white);
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shutdown/cancel_1.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout aboutUsPopLayout = new javax.swing.GroupLayout(aboutUsPop.getContentPane());
        aboutUsPop.getContentPane().setLayout(aboutUsPopLayout);
        aboutUsPopLayout.setHorizontalGroup(
            aboutUsPopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutUsPopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(aboutUsPopLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        aboutUsPopLayout.setVerticalGroup(
            aboutUsPopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutUsPopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(aboutUsPopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SHUTDOWN MENU");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(153, 255, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setFont(new java.awt.Font("Courier New", 0, 14));
        setForeground(new java.awt.Color(204, 255, 153));
        setName("frame"); // NOI18N
        setResizable(false);
        setUndecorated(true);

        jPanel1.setBackground(java.awt.SystemColor.textHighlight);
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 255), null, new java.awt.Color(255, 255, 255), new java.awt.Color(0, 51, 255)));
        jPanel1.setInheritsPopupMenu(true);

        restart.setBackground(new java.awt.Color(255, 255, 255));
        restart.setFont(new java.awt.Font("Segoe Print", 0, 14));
        restart.setForeground(new java.awt.Color(0, 102, 255));
        restart.setText("Restart");
        restart.setToolTipText("restart");
        restart.setBorderPainted(false);
        restart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                restartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                restartMouseExited(evt);
            }
        });
        restart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartActionPerformed(evt);
            }
        });

        shutdown.setBackground(new java.awt.Color(255, 255, 255));
        shutdown.setFont(new java.awt.Font("Segoe Print", 0, 14));
        shutdown.setForeground(new java.awt.Color(0, 102, 255));
        shutdown.setText("Shutdown");
        shutdown.setToolTipText("shutdown");
        shutdown.setBorder(null);
        shutdown.setFocusPainted(false);
        shutdown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                shutdownMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                shutdownMouseExited(evt);
            }
        });
        shutdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shutdownActionPerformed(evt);
            }
        });

        cancel.setBackground(new java.awt.Color(255, 255, 255));
        cancel.setFont(new java.awt.Font("Segoe Print", 0, 14));
        cancel.setForeground(new java.awt.Color(0, 102, 255));
        cancel.setText("Cancel");
        cancel.setToolTipText("cancel");
        cancel.setBorderPainted(false);
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelMouseExited(evt);
            }
        });
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        hibernate.setBackground(new java.awt.Color(255, 255, 255));
        hibernate.setFont(new java.awt.Font("Segoe Print", 0, 14));
        hibernate.setForeground(new java.awt.Color(0, 102, 255));
        hibernate.setText("Hibernate");
        hibernate.setToolTipText("Hibernate");
        hibernate.setBorderPainted(false);
        hibernate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hibernateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hibernateMouseExited(evt);
            }
        });
        hibernate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hibernateActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shutdown/Info_1.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(shutdown, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(restart, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hibernate, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cancel)
                        .addComponent(hibernate)
                        .addComponent(restart)
                        .addComponent(shutdown, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String lb=System.getProperty("line.separator");
    String cmd=new String("shutdown ");
    private void shutdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shutdownActionPerformed
        try{
        Runtime.getRuntime().exec(cmd+"-s -t 00 /hybrid");
        }
        catch(IOException e){}
//        JOptionPane.showMessageDialog(null,"Shutting-Down Shortly... "+lb+"Good Bye Sir !!");
        System.exit(0);
    }//GEN-LAST:event_shutdownActionPerformed

    private void restartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartActionPerformed
        try{
        Runtime.getRuntime().exec(cmd+"-r -t 00");
        }
        catch(IOException e){}
 //       JOptionPane.showMessageDialog(null,"Restarting Shortly "+lb+"See You Soon !!");
        System.exit(0);
    }//GEN-LAST:event_restartActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cancelActionPerformed

    private void shutdownMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shutdownMouseEntered
        shutdown.setBackground(Color.yellow);
    }//GEN-LAST:event_shutdownMouseEntered

    private void shutdownMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shutdownMouseExited
        shutdown.setBackground(Color.white);
    }//GEN-LAST:event_shutdownMouseExited

    private void restartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restartMouseEntered
        restart.setBackground(Color.yellow);
    }//GEN-LAST:event_restartMouseEntered

    private void restartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restartMouseExited
        restart.setBackground(Color.white);
    }//GEN-LAST:event_restartMouseExited

    private void cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseEntered
        cancel.setBackground(Color.yellow);
    }//GEN-LAST:event_cancelMouseEntered

    private void cancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseExited
        cancel.setBackground(Color.white);
    }//GEN-LAST:event_cancelMouseExited

    private void hibernateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hibernateActionPerformed
        try{
        Runtime.getRuntime().exec(cmd+"/h");
        }
        catch(IOException e){}
        System.exit(0);


    }//GEN-LAST:event_hibernateActionPerformed

    private void hibernateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hibernateMouseEntered
        hibernate.setBackground(Color.yellow);
    }//GEN-LAST:event_hibernateMouseEntered

    private void hibernateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hibernateMouseExited
        hibernate.setBackground(Color.white);
    }//GEN-LAST:event_hibernateMouseExited

    Icon i=new ImageIcon("Info_1.png");JTextArea jta=new JTextArea("Credits To Mr. Ajay Prem Shankar..(Dated: 20.12.2012)");

    private void aboutUsTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutUsTextMouseEntered
        authorPop.add(jta);
        authorPop.setLocation(600-31,450);
        authorPop.setVisible(true);
    }//GEN-LAST:event_aboutUsTextMouseEntered

    private void aboutUsTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutUsTextMouseExited
        authorPop.setVisible(false);
}//GEN-LAST:event_aboutUsTextMouseExited

    private void knowUsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_knowUsMouseClicked
        if(Desktop.isDesktopSupported()) {
            try{
                Desktop.getDesktop().browse(new URI("https://www.facebook.com/ForwardSlash.FW"));
            } catch(Exception e) {
            }
        }
}//GEN-LAST:event_knowUsMouseClicked

    private void knowUsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_knowUsMouseEntered
        knowUs.setCursor(new Cursor(Cursor.HAND_CURSOR));
        knowUs.setBackground(Color.LIGHT_GRAY);
}//GEN-LAST:event_knowUsMouseEntered

    private void knowUsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_knowUsMouseExited
        knowUs.setBackground(Color.WHITE);
}//GEN-LAST:event_knowUsMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        this.setVisible(false);
        aboutUsPop.setLocation(500,200);
        aboutUsPop.setSize(400,300);
        aboutUsPop.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        aboutUsPop.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Menu menu=new Menu();
                
                menu.setLocation(475,300);
                menu.setAlwaysOnTop(true);
                menu.jPanel1.setVisible(true);
                menu.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JDialog aboutUsPop;
    private javax.swing.JTextArea aboutUsText;
    private javax.swing.JPopupMenu authorPop;
    private javax.swing.JButton cancel;
    private javax.swing.JButton hibernate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane knowUs;
    private javax.swing.JButton restart;
    private javax.swing.JButton shutdown;
    // End of variables declaration//GEN-END:variables

}
